---
- name: Install (or update) docker.io
  apt: 
    name: docker.io 
    state: latest
    update_cache: yes
  when: "ansible_distribution_version == '14.04'"

- name: Link docker binaries
  file: 
    src: /usr/bin/docker.io 
    dest: /usr/local/bin/docker 
    owner: root 
    group: root 
    state: link
  when: "ansible_distribution_version == '14.04'"

- name: Check if docker installed
  command: /usr/bin/test -e /etc/default/docker.io
  register: docker_installed

- name: Enable bash completion
  command: sed -i '$acomplete -F _docker docker' /etc/bash_completion.d/docker.io
  when: docker_installed

- name: Expose docker host
  lineinfile: dest=/etc/default/docker.io regexp="^#DOCKER_OPTS.*" line="DOCKER_OPTS=\"-H unix:\/\/ -H tcp:\/\/{{ docker_host_ip }}:{{ docker_host_port }}\""
  notify: "restart docker"
  when: "docker_installed and export_docker_host"